# Generated by Django 5.2.7 on 2025-11-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10)),
                ('employee_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=30)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retirement', models.DateField()),
                ('other_benefits', models.TextField()),
                ('total_compensation', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
